### ISSUE TITLE
Pluto isn't able to find the juju binary

### ISSUE THREAD

**Issue by jamesbeedy** [NucciTheBoss/pluto#1]
### Bug Description

After installing pluto from the snap store with `sudo snap install pluto --edge` and running the `bootstrap` command, I get this error telling me that `juju` cannot be found.

```bash
$ sudo snap install pluto  --edge
pluto (edge) 0.1.0 from Jason Nucciarone (nuccitheboss) installed

$ pluto bootstrap test-cluster
Deploying cluster test-cluster. This will take several minutes...
Attaching NHC to compute nodes... - (2.8s)                                                                                                                                Traceback (most recent call last):
  File "/snap/pluto/3/bin/pluto", line 8, in <module>
    sys.exit(main())
  File "/snap/pluto/3/lib/python3.10/site-packages/pluto/main.py", line 49, in main
    exit_code = dispatcher.run()
  File "/snap/pluto/3/lib/python3.10/site-packages/craft_cli/dispatcher.py", line 448, in run
    return self._loaded_command.run(self._parsed_command_args)
  File "/snap/pluto/3/lib/python3.10/site-packages/pluto/cmd/bootstrap.py", line 328, in run
    loop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/snap/pluto/3/lib/python3.10/site-packages/pluto/cmd/bootstrap.py", line 208, in _bootstrap
    await cluster.attach_resource("compute", {"nhc": nhc})
  File "/snap/pluto/3/lib/python3.10/site-packages/pluto/drivers/cluster.py", line 156, in attach_resource
    await _juju("attach-resource", application_name, f"{k}={v}")
  File "/snap/pluto/3/lib/python3.10/site-packages/pluto/drivers/cluster.py", line 49, in _juju
    proc = await asyncio.create_subprocess_exec(
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1681, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/usr/lib/python3.10/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 799, in _start
    self._proc = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'juju'
```

### To Reproduce

To reproduce:
```bash
juju bootstrap localhost

lxc profile set default security.privileged true

lxc profile set default raw.apparmor 'mount fstype=nfs*, mount fstype=rpc_pipefs,'

sudo snap install pluto  --edge

pluto bootstrap test-cluster

```

### Environment

na

### Relevant log output

```shell
na
```

### Additional context

na

**Comment by jamesbeedy** [comment]
Works as expected when `pluto` is installed in a venv using `pip install .`
